# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do
  desc "Test and generate coverage"
  lane :test do
    scan(scheme: "Simplify-SDK-Swift")
    xcov(
      workspace: "Simplify-SDK-Swift.xcworkspace",
      scheme: "Simplify-SDK-Swift",
      output_directory: "fastlane/test_output/xcov"
    )
  end


  desc "Update the SDK version number for all frameworks in the project."
  lane :update_version do
    current_build_number = get_build_number(xcodeproj: "Simplify-SDK-Swift/Simplify-SDK-Swift.xcodeproj/")
    UI.message("Current SDK version: #{current_build_number}")
    version = UI.input("Enter the new SDK version Number:")

    increment_build_number(
      build_number: version,
      xcodeproj: "Simplify-SDK-Swift/Simplify-SDK-Swift.xcodeproj/"
    )
  end

  desc "Update generated documentation"
  lane :update_docs do
    Actions.verify_gem!('jazzy')
    # Fastlane runs in the ./fastlane foolder, so we need to go up a directory
    Dir.chdir("../") do
      Actions.sh("jazzy")
    end
  end

  desc "Prepare a release buy updating the version number and documentation"
  lane :prep_release do
    update_version
    update_docs
  end

end
